version: '3.3'
services:
  api:
    build: .
    container_name: hibisco-ws
    image: hibisco-ws:1.0
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      AZURE_URL: ${AZURE_URL}
      AZURE_USER: ${AZURE_USER}
      AZURE_PASSWORD: ${AZURE_PASSWORD}
      KEY_GOOGLE_MAPS: ${KEY_GOOGLE_MAPS}