spring:
  datasource:
    url: ${AZURE_URL}
    username: ${AZURE_USER}
    password: ${AZURE_PASSWORD}
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      format_sql: true
      dialect : org.hibernate.dialect.SQLServer2018Dialect

server:
  port: 8080

